In [38]:
from pathlib import Path
import pyarrow as pa
import pyarrow.compute as pc   
import pyarrow.dataset as ds   
import pyarrow.parquet as pq   
import pandas as pd
from rich import print as rprint
from rich.pretty import pprint

# path = Path('large2_raw_dataset')
path = Path('large2_ingested_dataset')
# path = Path('large2_compacted_dataset')

!tree $path | head -n 100

large2_ingested_dataset
├── year=2020
│   ├── month=1
│   │   ├── 0195fc56-5869-4c03-a012-2c214b27f8c1-0.parquet
│   │   ├── 050f1631-db4b-4902-a6b5-55625e78f2b0-0.parquet
│   │   ├── 05bad383-dc03-43f2-bb6f-f5141a450a7d-0.parquet
│   │   ├── 0c92a151-8259-4b81-9518-18171acef770-0.parquet
│   │   ├── 0dd21819-bb6e-4f04-936e-9fdb2e8988af-0.parquet
│   │   ├── 11c28f49-ee96-495b-aa01-d7f28db7a7bb-0.parquet
│   │   ├── 14688a3d-d27e-4ec8-bd7e-4874ecc00a6f-0.parquet
│   │   ├── 15f0704e-f4ef-45fd-94a8-e081ef6d854b-0.parquet
│   │   ├── 16e3bb07-7ed8-41dd-9d5f-9c456c215d90-0.parquet
│   │   ├── 20ee14b3-1f70-4f5b-af8b-ea0f7099a20f-0.parquet
│   │   ├── 21ce7083-cc30-4a78-b9c0-70ed5f769416-0.parquet
│   │   ├── 24e89b88-09df-40ed-aeec-92c7db51db02-0.parquet
│   │   ├── 27ca8d8c-a94a-4894-bec8-4c90d2fde090-0.parquet
│   │   ├── 2a1df980-b4df-4131-b2f2-700b955367a6-0.parquet
│   │   ├── 2a40f928-c0a1-49ff-9cbc-40914b84dd1b-0.parquet
│   │   ├── 2ab75bff-f84d-402f-8c2c-45534fceb7fe-0.parquet
│   │   ├── 2b8dfdaf-089b-4b0b-9421-d9ceaab021d1-0.parquet
│   │   ├── 2c75835f-1fe1-4749-ab78-ea204b7d0b42-0.parquet
│   │   ├── 2cdb523d-8096-4d90-ac2c-701484c5056d-0.parquet
│   │   ├── 2ce48169-87a8-4bc0-bda2-68cf70f4702f-0.parquet
│   │   ├── 31c19ee1-9a0b-411c-aca0-398a19602483-0.parquet
│   │   ├── 326c9ae2-44ee-40d5-a696-799f73c19cd8-0.parquet
│   │   ├── 327b2733-ce15-47ef-9f24-2ae651f746eb-0.parquet
│   │   ├── 3605a09e-d03b-4cf8-9e24-5f97b59d4d65-0.parquet
│   │   ├── 379cbb9c-85bb-493e-af07-e16590a3bb7b-0.parquet
│   │   ├── 387706af-bf0a-4b57-9b0a-59b9a9baf274-0.parquet
│   │   ├── 38d7309e-c8e4-43b0-93ff-a7b8128f0cdd-0.parquet
│   │   ├── 3bb8a15b-f440-4970-98b5-bb1877df55ee-0.parquet
│   │   ├── 3eea715b-55c1-4085-8fbb-1ae74dba8574-0.parquet
│   │   ├── 46ce368d-b610-4efb-860c-675d5a87047f-0.parquet
│   │   ├── 47dca7b4-ebc1-43b0-927f-6aa94aab4b8a-0.parquet
│   │   ├── 4b8fd8e4-5cbb-414c-9604-69078f8577f4-0.parquet
│   │   ├── 4f14e077-8e51-4898-b028-d6a94d7b993b-0.parquet
│   │   ├── 505072d2-0cfa-4189-a406-95cbda3e044f-0.parquet
│   │   ├── 51917e82-abeb-493a-914c-fa57082ece82-0.parquet
│   │   ├── 51b4e73c-ac14-454a-94e9-ac0bdfb60245-0.parquet
│   │   ├── 544c1600-ed00-46ca-98c8-f5b38c0d24d1-0.parquet
│   │   ├── 56b8143f-78c2-4abb-9e05-1c25a90b2163-0.parquet
│   │   ├── 58783820-c6ee-4639-a335-2b043e5ca1b7-0.parquet
│   │   ├── 5a26b054-de4d-44ce-869c-3a89eb9e9167-0.parquet
│   │   ├── 5d2fe31c-923c-407f-add9-cf1bfeb3d2d4-0.parquet
│   │   ├── 5d8287ab-4787-446d-91e9-6873c0299d4f-0.parquet
│   │   ├── 5ea98af1-b0af-47c9-83ec-994dad73b2a2-0.parquet
│   │   ├── 6133f395-be4c-47cf-845f-262be5d6ceb1-0.parquet
│   │   ├── 61e9e31d-804b-4e39-b56c-3a2fedcf4540-0.parquet
│   │   ├── 61eee9e4-d29e-43f7-a725-9998ad5aae64-0.parquet
│   │   ├── 633aa6d1-43aa-4857-80f1-9a29af5e888e-0.parquet
│   │   ├── 642a6600-b566-47bc-8dd5-088fe4e77f1c-0.parquet
│   │   ├── 65b7f0d8-0153-43ec-aace-196ee32b1b44-0.parquet
│   │   ├── 6682d054-f4ed-4672-b226-a4007cf2b914-0.parquet
│   │   ├── 69a83acc-eda3-4f60-bc09-798eec52dead-0.parquet
│   │   ├── 714fb273-c1ca-4894-b98a-749bd0c25ecb-0.parquet
│   │   ├── 71ec8646-0578-4fd1-9dd6-380a84694d62-0.parquet
│   │   ├── 74666abd-71bc-46d0-ac82-5c0e257ca728-0.parquet
│   │   ├── 770552c1-a82f-4588-a2ad-444844af5679-0.parquet
│   │   ├── 815989ab-d93b-46be-bb34-c957bef5e581-0.parquet
│   │   ├── 81eb96fc-e321-445e-be4a-0c7b60154942-0.parquet
│   │   ├── 83415eba-4f78-48ad-a1bb-377bb9b655dd-0.parquet
│   │   ├── 852d38fd-0bc9-4dcc-b285-15c99ef3241a-0.parquet
│   │   ├── 885ac04c-9efe-483a-8541-53f22669f2ca-0.parquet
│   │   ├── 88ab0d2a-ae03-4453-b40b-ba3d1ce3df95-0.parquet
│   │   ├── 8914fef7-2ac4-4ee3-8823-66e549ab5d76-0.parquet
│   │   ├── 8befa2ef-f392-4275-9260-84bc541cf9b6-0.parquet
│   │   ├── 8c2d861b-e2b7-4408-bfe2-229cd0e4627c-0.parquet
│   │   ├── 8d6e9806-902e-4615-b471-8c14992c9680-0.parquet
│   │   ├── 8d92025c-47bf-4cc3-aae6-b8f78773cd17-0.parquet
│   │   ├── 908de1bd-cc0c-4477-871e-fe632020f1ee-0.parquet
│   │   ├── 90b5f693-3a9c-4bd7-b723-04ce9463abea-0.parquet
│   │   ├── 91109202-1d6a-4bb7-9f0f-b96c1f562ff7-0.parquet
│   │   ├── 912a17f8-6efd-417f-9c3c-471227e6ffbc-0.parquet
│   │   ├── 914b094f-bc85-449e-95e5-c3b67caabef0-0.parquet
│   │   ├── 9243616f-7195-4a5d-af80-0604366e352a-0.parquet
│   │   ├── 957a4547-7695-493f-bc7d-af19aa61eafb-0.parquet
│   │   ├── 9a18f157-03a2-4498-bc31-0490fa3a9d59-0.parquet
│   │   ├── 9d6442b4-3957-4352-abce-934cbd2d6235-0.parquet
│   │   ├── a023b08b-8f13-41ae-9238-2ec70a7ef9b5-0.parquet
│   │   ├── a20a3541-a97c-40b5-9b34-1326a639835c-0.parquet
│   │   ├── a421aa5b-7a3f-4564-b33e-9473ce292db7-0.parquet
│   │   ├── a5c0b0e9-2fe0-4295-9bc4-810c9e2c5c3e-0.parquet
│   │   ├── a62a6121-8ec7-4966-85c8-b446fcc6dd19-0.parquet
│   │   ├── aa9d7a1b-fa2c-4096-bd58-c5411be8b480-0.parquet
│   │   ├── af5ffc6e-69e2-4f0e-aec1-8954723de91b-0.parquet
│   │   ├── b10f05e3-e927-4a29-a2f8-7b98c1bd3351-0.parquet
│   │   ├── b1c4db2d-7157-4449-a4d8-a5c97671e830-0.parquet
│   │   ├── b5f2e1c4-32b9-4aa7-9034-73c9328a8676-0.parquet
│   │   ├── b6ea0b1f-68d6-4a0a-a727-c09c9d270352-0.parquet
│   │   ├── bd1dc526-9eff-4677-9854-5ea95d9b5db6-0.parquet
│   │   ├── c078b2f2-dd5b-49af-adb6-6f2bfecee095-0.parquet
│   │   ├── c0f4cd40-269d-42fc-b090-ca02dc854b4e-0.parquet
│   │   ├── c10648df-e875-4551-9029-fd41ac852df2-0.parquet
│   │   ├── c7c18035-5aff-46fa-9b2c-52b58bf5befb-0.parquet
│   │   ├── c9a9a178-aca8-41e0-928b-379b82b653d2-0.parquet
│   │   ├── c9cc8105-e88f-4daf-809c-8c7a025b525b-0.parquet
│   │   ├── ccdfc0c9-2303-40ab-a7d8-32ab0623b64c-0.parquet
│   │   ├── cce88d9b-2d23-4360-bb4f-f6e5c09b5bd8-0.parquet
│   │   ├── cd38be33-d6f5-4bed-9d65-65966a1b328e-0.parquet
│   │   ├── ce544410-15ae-4ec7-a87c-b245818f8e32-0.parquet

# Query: get a single file

In [81]:
single_parquet = Path('large2_ingested_dataset/year=2020/month=1/0195fc56-5869-4c03-a012-2c214b27f8c1-0.parquet')
single_parquet

PosixPath('large2_ingested_dataset/year=2020/month=1/0195fc56-5869-4c03-a012-2c214b27f8c1-0.parquet')

In [82]:
df1 = pd.read_parquet(single_parquet)

In [83]:
df2 = pq.read_table(single_parquet).to_pandas()

In [84]:
df3 = ds.dataset(single_parquet).to_table().to_pandas()

In [85]:
assert all([df1.equals(df2), df1.equals(df3), df2.equals(df3)])

In [86]:
df1

,datetime,cat_col_00,cat_col_01,cat_col_02,num_col_00,num_col_01,num_col_02,num_col_03,num_col_04,num_col_05,num_col_06,num_col_07,num_col_08,num_col_09,batch,day
0,2020-01-01 18:00:00.000,baz,blue,buzz,2.168499,1.654215,0.468766,0.441180,-0.007433,0.270111,-0.070947,0.817798,-0.527300,0.038718,3,1
1,2020-01-01 18:00:00.216,foo,red,buzz,-0.439718,-0.362310,-0.322030,0.055357,-0.934949,-0.528707,0.695108,0.508217,1.058764,-1.050477,3,1
2,2020-01-01 18:00:00.432,bar,blue,buzz,0.072082,0.432789,0.557355,0.101657,0.327061,-0.258815,1.270834,0.123651,0.914242,0.433152,3,1
3,2020-01-01 18:00:00.648,baz,blue,buzz,-1.433295,-2.397422,-0.269227,-1.252177,0.399687,-1.898490,1.254852,1.357331,-1.708340,1.058333,3,1
4,2020-01-01 18:00:00.864,baz,blue,fizz,1.280217,-0.953454,1.029969,-0.215149,-1.107915,-0.380019,-0.229402,1.310755,-0.617757,-1.589411,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2020-01-01 23:59:58.920,bar,red,buzz,0.001542,-0.262291,0.471803,-0.191881,-0.846244,0.467656,-1.601341,-0.877223,-0.739573,-1.547508,3,1
99996,2020-01-01 23:59:59.136,baz,blue,buzz,0.457671,-0.049440,-1.236890,-1.325623,-0.959757,0.073846,0.509169,0.108377,1.541676,0.408273,3,1
99997,2020-01-01 23:59:59.352,bar,red,fizz,0.967025,0.639978,-0.263556,-1.986120,1.901012,-0.696059,-0.597016,-1.377537,-0.686801,-0.281780,3,1
99998,2020-01-01 23:59:59.568,bar,green,fizz,0.081316,0.043774,-0.875723,-0.616163,1.140218,-0.249316,-1.149716,-0.264902,-0.653788,-0.645275,3,1
99999,2020-01-01 23:59:59.784,bar,blue,buzz,-0.393765,-0.991100,0.425164,-1.601643,0.533317,0.878152,-1.623865,1.573340,-0.046015,-0.458769,3,1

In [87]:
%timeit ds.dataset(single_parquet).to_table().to_pandas()

4.46 ms ± 52 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# Query: get a single batch

In [88]:
path = Path('large2_compacted_dataset')
dataset = ds.dataset(path, partitioning='hive')

In [89]:
filters = pq._filters_to_expression([
    ('batch', '=', 3),
])

df = dataset.to_table(filter=filters).to_pandas()
df

,datetime,cat_col_00,cat_col_01,cat_col_02,num_col_00,num_col_01,num_col_02,num_col_03,num_col_04,num_col_05,num_col_06,num_col_07,num_col_08,num_col_09,batch,day,year,month
0,2020-01-01 18:00:00.000,baz,blue,buzz,2.168499,1.654215,0.468766,0.441180,-0.007433,0.270111,-0.070947,0.817798,-0.527300,0.038718,3,1,2020,1
1,2020-01-01 18:00:00.216,foo,red,buzz,-0.439718,-0.362310,-0.322030,0.055357,-0.934949,-0.528707,0.695108,0.508217,1.058764,-1.050477,3,1,2020,1
2,2020-01-01 18:00:00.432,bar,blue,buzz,0.072082,0.432789,0.557355,0.101657,0.327061,-0.258815,1.270834,0.123651,0.914242,0.433152,3,1,2020,1
3,2020-01-01 18:00:00.648,baz,blue,buzz,-1.433295,-2.397422,-0.269227,-1.252177,0.399687,-1.898490,1.254852,1.357331,-1.708340,1.058333,3,1,2020,1
4,2020-01-01 18:00:00.864,baz,blue,fizz,1.280217,-0.953454,1.029969,-0.215149,-1.107915,-0.380019,-0.229402,1.310755,-0.617757,-1.589411,3,1,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2020-01-01 23:59:58.920,bar,red,buzz,0.001542,-0.262291,0.471803,-0.191881,-0.846244,0.467656,-1.601341,-0.877223,-0.739573,-1.547508,3,1,2020,1
99996,2020-01-01 23:59:59.136,baz,blue,buzz,0.457671,-0.049440,-1.236890,-1.325623,-0.959757,0.073846,0.509169,0.108377,1.541676,0.408273,3,1,2020,1
99997,2020-01-01 23:59:59.352,bar,red,fizz,0.967025,0.639978,-0.263556,-1.986120,1.901012,-0.696059,-0.597016,-1.377537,-0.686801,-0.281780,3,1,2020,1
99998,2020-01-01 23:59:59.568,bar,green,fizz,0.081316,0.043774,-0.875723,-0.616163,1.140218,-0.249316,-1.149716,-0.264902,-0.653788,-0.645275,3,1,2020,1
99999,2020-01-01 23:59:59.784,bar,blue,buzz,-0.393765,-0.991100,0.425164,-1.601643,0.533317,0.878152,-1.623865,1.573340,-0.046015,-0.458769,3,1,2020,1

In [90]:
%timeit dataset.to_table(filter=filters).to_pandas()

8.01 ms ± 70 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [103]:
assert df.drop(columns=['year', 'month']).equals(df1)

# Query: compute min/max

In [67]:
path = Path('large2_compacted_dataset')
dataset = ds.dataset(path, partitioning='hive')

In [68]:
datetime = dataset.to_table(columns=['datetime']).column('datetime')
pc.min_max(datetime).as_py()

{'min': Timestamp('2020-01-01 00:00:00'),
 'max': Timestamp('2022-01-19 23:59:59.784000')}

# Query: column and row filter

In [ ]:
path = Path('large2_compacted_dataset')
dataset = ds.dataset(path, partitioning='hive')

In [69]:
columns = ['datetime', 'cat_col_01', 'num_col_01']  # column projection
filters = pq._filters_to_expression([               # partition + row_group pruning
    ('year', '=', 2020),
    ('month', '<', 4),
    ('day', '<', 5),
    ('cat_col_00', '=', 'foo')
])

table = dataset.to_table(columns=columns, filter=filters)

In [70]:
table.to_pandas()

                       datetime cat_col_01  num_col_01
0       2020-01-01 18:00:00.216        red   -0.362310
1       2020-01-01 18:00:02.160      green    1.620285
2       2020-01-01 18:00:04.752        red   -0.753150
3       2020-01-01 18:00:05.400        red   -0.701831
4       2020-01-01 18:00:06.048      green    1.125831
...                         ...        ...         ...
1599974 2020-03-04 23:59:53.736       blue    1.500787
1599975 2020-03-04 23:59:54.168      green    1.855265
1599976 2020-03-04 23:59:54.600      green   -0.310330
1599977 2020-03-04 23:59:57.624        red    0.186751
1599978 2020-03-04 23:59:58.920       blue    1.032602

[1599979 rows x 3 columns]

# Bulk Read

In [ ]:
path = Path('large2_compacted_dataset')
dataset = ds.dataset(path, partitioning='hive')

In [104]:
model = get_trained_model()
for i, batch in enumerate(dataset.to_batches()):
    df_batch = batch.to_pandas()
    print(f'Training on batch {df_batch.batch.unique()}')
    # Incremental training
    model.incremental_train(df_batch)
    
    if i > 100: break

Training on batch [3]
Training on batch [20]
Training on batch [68]
Training on batch [102]
Training on batch [111]
Training on batch [43]
Training on batch [58]
Training on batch [38]
Training on batch [109]
Training on batch [100]
Training on batch [80]
Training on batch [117]
Training on batch [49]
Training on batch [0]
Training on batch [91]
Training on batch [42]
Training on batch [57]
Training on batch [29]
Training on batch [39]
Training on batch [28]
Training on batch [96]
Training on batch [12]
Training on batch [83]
Training on batch [84]
Training on batch [19]
Training on batch [75]
Training on batch [5]
Training on batch [74]
Training on batch [44]
Training on batch [6]
Training on batch [36]
Training on batch [120]
Training on batch [122]
Training on batch [76]
Training on batch [66]
Training on batch [98]
Training on batch [15]
Training on batch [78]
Training on batch [103]
Training on batch [67]
Training on batch [110]
Training on batch [61]
Training on batch [85]
Training on batch [81]
Training on batch [18]
Training on batch [51]
Training on batch [27]
Training on batch [33]
Training on batch [47]
Training on batch [21]
Training on batch [37]
Training on batch [95]
Training on batch [34]
Training on batch [22]
Training on batch [31]
Training on batch [52]
Training on batch [99]
Training on batch [105]
Training on batch [13]
Training on batch [53]
Training on batch [4]
Training on batch [26]
Training on batch [88]
Training on batch [93]
Training on batch [71]
Training on batch [9]
Training on batch [90]
Training on batch [35]
Training on batch [106]
Training on batch [108]
Training on batch [89]
Training on batch [41]
Training on batch [30]
Training on batch [72]
Training on batch [14]
Training on batch [92]
Training on batch [65]
Training on batch [123]
Training on batch [48]
Training on batch [40]
Training on batch [119]
Training on batch [16]
Training on batch [45]
Training on batch [54]
Training on batch [23]
Training on batch [46]
Training on batch [79]
Training on batch [63]
Training on batch [64]
Training on batch [25]
Training on batch [56]
Training on batch [82]
Training on batch [24]
Training on batch [62]
Training on batch [1]
Training on batch [8]
Training on batch [94]
Training on batch [11]
Training on batch [59]
Training on batch [10]
Training on batch [2]
Training on batch [114]